version: 2

defaults: &defaults
  working_directory: ~/redux-cache-key-util
  docker:
    - image: circleci/node:carbon

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - dependency-cache-{{ checksum "package.json" }}-
            - dependency-cache-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Check linters
          command: yarn lint

  check-lockfile:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run lockfile linter
          command: yarn check-lockfile -p yarn.lock
      - run:
          name: Check for duplicate dependencies
          command: yarn yarn-deduplicate -f -l

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Copy/Upload Results
          command: |
            mkdir -p ./test-results/mocha
            [[ -e ./test-results.xml ]] && cp ./test-results.xml ./test-results/mocha/test-results.xml
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: test-results

  maybe_deploy:
    # Tag filtering in CircleCI is unreliable - this is hacky, but it works
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Maybe Deploy
          command: |
            # deploy tagged commits only
            if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> ~/.npmrc
            yarn build
            npm publish --scope=@dragonlabs --access public

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - check-lockfile:
          requires:
            - setup
      - test:
          requires:
            - setup
      - maybe_deploy:
          requires:
            - lint
            - check-lockfile
            - test
